version: '3.7'

services:
  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=outboxer
      - POSTGRES_PASSWORD=outboxer-pwd
    command:
      - '-cwal_level=logical'
      - '-cmax_wal_senders=1'
      - '-cmax_replication_slots=1'
    ports:
      - 5432:5432
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: 'S0m3_R4bBi7_C0ok13'
      RABBITMQ_DEFAULT_USER: 'rabbit_adm'
      RABBITMQ_DEFAULT_PASS: 'R4bb!7_4DM_p4SS'
    ports:
      - "15672:15672"
      - "5672:5672"
  outboxer:
    image: outboxer-postgres2rabbitmq
    build:
      context: ".."
    #volumes:
    #  - outboxer-data:/data
    environment:
      - OUTBOXER_DATABASE_HOSTNAME=database
      - OUTBOXER_DATABASE_PORT=5432
      - OUTBOXER_DATABASE_USER=outboxer
      - OUTBOXER_DATABASE_PASSWORD=outboxer-pwd
      - OUTBOXER_DATABASE_DBNAME=outboxer
      - OUTBOXER_DATABASE_SERVER_NAME=outboxer
      # Add heartbeat so outboxer fails faster in case of an database failure
      - OUTBOXER_HEARTBEAT_INTERVAL_MS=60000
      - OUTBOXER_HEARTBEAT_ACTION_QUERY=SELECT 1
      # Configure AMQP connection
      - OUTBOXER_PUBLISHER_AMQP_URL=amqp://rabbit_adm:R4bb!7_4DM_p4SS@rabbitmq:5672
      - OUTBOXER_PUBLISHER_AMQP_EXCHANGE=ods_global
      - OUTBOXER_PUBLISHER_AMQP_RETRIES=5
      - OUTBOXER_PUBLISHER_AMQP_RETRY_DELAY_MS=5000
      # only retry start once for test cases, so we have a more predictable behaviour
      - OUTBOXER_START_RETRY_COUNT=1
      - OUTBOXER_START_RETRY_DELAY_MS=2000
      #- OUTBOXER_OFFSET_STORAGE_FILE_FILENAME=/data/offset.dat
    depends_on:
      - database
      - rabbitmq

#volumes:
#  outboxer-data:
