name: Outboxer

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t outboxer-postgres2rabbitmq .
      - name: Save Docker image as artifact
        run: docker save outboxer-postgres2rabbitmq > outboxer.tar
      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v1
        with:
          name: outboxer-artifact
          path: outboxer.tar

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: outboxer-artifact
      - name: Load docker image from artifact
        run: docker load -i ./outboxer-artifact/outboxer.tar
      - name: Install dependencies
        working-directory: ./integration-test
        run: npm ci
      - name: Execute test
        working-directory: ./integration-test
        run: npm run test

# Authentication to GitHub container registry is only possible with an personal access token (PAT)
# The publish job requires a secret named `GHCR_PAT` which must contain a PAT with the `read:packages`
# and `write:packages` scope.
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [test]
    if: github.repository == 'jvalue/outboxer-postgres2rabbitmq' && github.ref == 'refs/heads/main'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: outboxer-artifact
      - name: Load docker image from artifact
        run: docker load -i ./outboxer-artifact/outboxer.tar
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Push to GitHub container registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/outboxer-postgres2rabbitmq
          docker tag outboxer-postgres2rabbitmq:latest $IMAGE_ID:latest
          docker push $IMAGE_ID:latest
